version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.41.1-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add components
          command: rustup component add clippy rustfmt
      - restore_cache:
          keys:
            - v1-cargo-lock-{{ checksum "Cargo.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-cargo-lock-
      - run:
          name: Format check
          command: cargo fmt -- --check
      - run:
          name: Lint
          command: cargo clippy -- -D warnings
      - run:
          name: Build
          command: cargo build
      - run:
          name: Run tests
          command: cargo test
      - save_cache:
          key: v1-cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - target
